DROP SEQUENCE alert_config_sequence;

DROP TABLE managing_key_log;
DROP TABLE notif_log;
DROP TABLE acknowledgement_log;
DROP TABLE alert_incident_log;
DROP TABLE notif_mapping;
DROP TABLE notif_config;
DROP TABLE managing_key_mapping;
DROP TABLE threshold_context_attr;
DROP TABLE threshold_qualifying_attr;
DROP TABLE threshold_config;
DROP TABLE notif_group_mapping;
DROP TABLE alerting_config;
DROP TABLE level_config;
DROP TABLE notif_group;
DROP TABLE managing_key;
DROP TABLE messaging_description;
DROP TABLE person;