CREATE TABLE HOST_EVENTS_16X (
	HOST_ID         INTEGER NOT NULL,
	EVENT_TYPE_ID   INTEGER NOT NULL,
	TS TIMESTAMP    NOT NULL,
	ENTRY_MODE      CHAR(1),
	ENTRY_PART_1    VARCHAR(2000),
	ENTRY_PART_2    VARCHAR(2000),
	ENTRY           VARCHAR(1),
	PRIMARY KEY ( HOST_ID, EVENT_TYPE_ID, TS )
)
;

CREATE TABLE PATH_EVENTS_16X (
	PATH_ID INTEGER NOT NULL,
	TYPE_ID INTEGER NOT NULL,
	EVENT_TYPE_ID INTEGER NOT NULL,
	TS TIMESTAMP NOT NULL,
	ENTRY_MODE CHAR(1),
	ENTRY_PART_1 VARCHAR(2000),
	ENTRY_PART_2 VARCHAR(2000),
	ENTRY VARCHAR(1),
	PRIMARY KEY ( PATH_ID, TYPE_ID, EVENT_TYPE_ID, TS )
)
;

CREATE TABLE TYPE_EVENTS_16X (
	TYPE_ID INTEGER NOT NULL,
	EVENT_TYPE_ID INTEGER NOT NULL,
	TS TIMESTAMP NOT NULL,
	ENTRY_MODE CHAR(1),
	ENTRY_PART_1 VARCHAR(2000),
	ENTRY_PART_2 VARCHAR(2000),
	ENTRY VARCHAR(1),
	PRIMARY KEY ( TYPE_ID, EVENT_TYPE_ID, TS )
)
;
